openapiOptions:
  file:
    - file: "storespb/messages.proto"
      option:
        info:
          title: Store Management
          version: "1.0.0"
        basePath: /
  method:
    - method: storespb.Stores.CreateStore
      option:
        operationId: createStore
        tags:
          - Store
        summary: Create a new store
    - method: storespb.Stores.GetStores
      option:
        operationId: getStores
        tags:
          - Store
        summary: Get a list of stores
    - method: storespb.Stores.GetStore
      option:
        operationId: getStore
        tags:
          - Store
        summary: Get a store
    - method: storespb.Stores.EnableParticipation
      option:
        operationId: enableParticipation
        tags:
          - Participation
        summary: Enable store service participation
    - method: storespb.Stores.DisableParticipation
      option:
        operationId: disableParticipation
        tags:
          - Participation
        summary: Disable store service participation
    - method: storespb.Stores.GetParticipatingStores
      option:
        operationId: getParticipatingStores
        tags:
          - Participation
        summary: Get a list of participating stores
    - method: storespb.Stores.AddProduct
      option:
        operationId: addProduct
        tags:
          - Product
        summary: Add a store product
    - method: storespb.Stores.GetProduct
      option:
        operationId: getProduct
        tags:
          - Product
        summary: Get a store product
    - method: storespb.Stores.RemoveProduct
      option:
        operationId: removeProduct
        tags:
          - Product
        summary: Remove a store product
    - method: storespb.Stores.GetCatalog
      option:
        operationId: getStoreProduct
        tags:
          - Product
        summary: Get a list of store products
